version: '3.7'
services:
  ze-mysql:
    image: linuxhub/mysql:5.7.28
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.app == mysql
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    ports:
      - '3306:3306'
    volumes:
      - /data/mysql/ze-mysql:/var/lib/mysql
    configs:
        - source: ze-mysql
          target: /etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        TZ: "Asia/Shanghai"

  ze-mysql-slave:
    image: linuxhub/mysql:5.7.28
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.app == mysql-slave
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    ports:
      - '3307:3306'
    volumes:
      - /data/mysql/ze-mysql-slave:/var/lib/mysql
    configs:
        - source: ze-mysql-slave
          target: /etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        TZ: "Asia/Shanghai"

configs:
    ze-mysql:
        file: ../assets/mysqld.cnf
    ze-mysql-slave:
        file: ../assets/mysqld-slave.cnf
